substitutions:
  name: aesgi
  device_description: "Monitor and control a AE Conversion inverter via RS485"
  external_components_source: github://syssi/esphome-aesgi@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-aesgi"
    version: 1.0.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

aesgi_rs485:
  - id: bus0
    uart_id: uart_0
    rx_timeout: 250ms

aesgi:
  - id: inverter0
    aesgi_rs485_id: bus0
    address: 29
    update_interval: 5s

binary_sensor:
  - platform: aesgi
    aesgi_id: inverter0
    online_status:
      name: "${name} online status"

sensor:
  - platform: aesgi
    aesgi_id: inverter0
    status:
      name: "${name} status"
    dc_voltage:
      name: "${name} DC voltage"
    dc_current:
      name: "${name} DC current"
    dc_power:
      name: "${name} DC power"
    ac_voltage:
      name: "${name} AC voltage"
    ac_current:
      name: "${name} AC current"
    ac_power:
      name: "${name} AC power"
    device_temperature:
      name: "${name} device temperature"
    energy_today:
      name: "${name} energy today"
    output_power:
      name: "${name} output power"
    current_limit:
      name: "${name} current limit"
    voltage_limit:
      name: "${name} voltage limit"
    uptime:
      name: "${name} uptime"
    ac_voltage_nominal:
      name: "${name} AC voltage nominal"
    ac_frequency_nominal:
      name: "${name} AC frequency nominal"
    ac_voltage_upper_limit:
      name: "${name} AC voltage upper limit"
    ac_voltage_upper_limit_delay:
      name: "${name} AC voltage upper limit delay"
    ac_voltage_lower_limit:
      name: "${name} AC voltage lower limit"
    ac_voltage_lower_limit_delay:
      name: "${name} AC voltage lower limit delay"
    ac_frequency_upper_limit:
      name: "${name} AC frequency upper limit"
    ac_frequency_upper_limit_delay:
      name: "${name} AC frequency upper limit delay"
    ac_frequency_lower_limit:
      name: "${name} AC frequency lower limit"

    error_history_slot1_error_code:
      name: "${name} error history slot1 error code"
    error_history_slot1_error_time:
      name: "${name} error history slot1 error time"
    error_history_slot2_error_code:
      name: "${name} error history slot2 error code"
    error_history_slot2_error_time:
      name: "${name} error history slot2 error time"
    error_history_slot3_error_code:
      name: "${name} error history slot3 error code"
    error_history_slot3_error_time:
      name: "${name} error history slot3 error time"
    error_history_slot4_error_code:
      name: "${name} error history slot4 error code"
    error_history_slot4_error_time:
      name: "${name} error history slot4 error time"
    error_history_slot5_error_code:
      name: "${name} error history slot5 error code"
    error_history_slot5_error_time:
      name: "${name} error history slot5 error time"
    # This is the most recent error
    error_history_slot6_error_code:
      name: "${name} error history slot6 error code"
    error_history_slot6_error_time:
      name: "${name} error history slot6 error time"

text_sensor:
  - platform: aesgi
    aesgi_id: inverter0
    operation_mode:
      name: "${name} operation mode"
    errors:
      name: "${name} errors"
    device_type:
      name: "${name} device type"
