substitutions:
  name: aesgi
  device_description: "Monitor and control a AE Conversion inverter via RS485"
  external_components_source: github://syssi/esphome-aesgi@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-aesgi"
    version: 1.0.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

aesgi_rs485:
  - id: bus0
    uart_id: uart_0
    rx_timeout: 250ms

aesgi:
  - id: inverter0
    aesgi_rs485_id: bus0
    address: 29
    update_interval: 5s

binary_sensor:
  - platform: aesgi
    online_status:
      name: "${name} online status"

sensor:
  - platform: aesgi
    status:
      name: "${name} status"
    dc_voltage:
      name: "${name} dc voltage"
    dc_current:
      name: "${name} dc current"
    dc_power:
      name: "${name} dc power"
    ac_voltage:
      name: "${name} ac voltage"
    ac_current:
      name: "${name} ac current"
    ac_power:
      name: "${name} ac power"
    device_temperature:
      name: "${name} device temperature"
    energy_today:
      name: "${name} energy today"
    output_power:
      name: "${name} output power"
    current_limit:
      name: "${name} current limit"
    voltage_limit:
      name: "${name} voltage limit"

text_sensor:
  - platform: aesgi
    operation_mode:
      name: "${name} operation mode"
    errors:
      name: "${name} errors"
    device_type:
      name: "${name} device type"
